### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by marianikitha01** [INFO526-DataViz/project-01-Aes-thetics-Squad#2]
The following is the peer review of the project proposal by Plotting Pandas. The team members that participated in this review are 

- Maria Nikitha Suresh - @marianikitha01
- Megan Hokama - @meganhokama
- Shakir Ahmed - @Shakir0585
- Eshaan Mathakari.- @eshaanmathakari
- Bharath Velamala - @bharath03-a

- Describe the goal of the project.
The project aims to examine the Tornado dataset with the goal of studying patterns and trends of tornado behaviors within the United States. Based on the research questions posed, the goal is to identify the impacts of tornados in various states within the United States, as well as, find relationships between the magnitude of the tornado and the location or year. Additionally, they ultimately want to build models that could showcase these patterns utilizing plot analyses and potentially create predictive models.

- Describe the data used or collected.
The data used here is having 68693 rows and 27 columns with important columns like time of occurence, magnitude on F scale, number of injuries, fatalities, estimated property loss in dollars, longitudes and latitudes. And the data is raninging from 1950 to 2022 tornado events. The columns which are being used for visualisation are mag, st, yr, om, ns, sn, st which are described in the proposal. Looking at the proposal we can find that most of the data contains the parameters related to effect of tornados and also where and when the tonrados occured.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
1. For Question 1, there are two tables which are going to used for plotting. One is going to be grouped using the group_by() function. The second is going to be grouped by years. Both these datasets are going to be plotted in the form of an alley map visualization to determine if there are any states which have undergone any variation in magnitude over time.
2. For Question 2, there is going to be data manipulation (mutate) to filter for tornadoes which affect more than one state at a time with the parameter 'ns>1'. Further, there is going be identifying of tornadoes by ID, and find out how many states it affects at one time. Heatmaps or Barplot is going to be used to visualise the co-occurrence patterns between states, and to find out the states which are more likely to get hit by a tornado, and also patterns of multi-state impact of tornadoes and re-occurring patterns in tornado data.

- Is there anything that is unclear from the proposal?
It's a little challenging to understand the first question's methodology. Additionally, we believe that the rationale for selecting the visualization of alley maps may have been stated in the text.

- Provide constructive feedback on how the team might be able to improve their project.
1. Project title is missing in the navbar, it will be cool to add it :)
2. It would have been nice to have your information written in the about page since it will give us some insight on who has done the project.
3. In the first code chuck, since while installing packages the run output might be too long some times to show it on a webpage, it would be better to not include the output using include=FALSE .

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
We would be interested in visualizing the patterns in the magnitude of tornadoes based on location or time of year as this could help us predict tornadoes and finding a relation between natural calamities and external factors affecting it could be interesting and would like it if they could visualize it with their backed up research regarding same.

- Provide constructive feedback on any issues with file and/or code organization.
1. Issues with inline variables: Where there are variables mentioned. It seemed like the formatting is not done correctly as we can see so characters like (`) which we use for highlighting purposes.
2. Also the scales of the parameters wasn't defined eg: E-F scale is unclear to what is stands for and range of the scales.

- (Optional) Any further comments or feedback?
 1. After glancing through the code, we noticed that labels and code chunk parameters are being used twice for same code chunk. This might be redundant.
2. Analysis section needed a re-read multiple times to understand the specifics as the outline was unclear on the data visualization. It could have been made better by defining the type of plot first, and then following through with the definitions and approach, as we would have a mental map as to what the data visualization could look like.

Overall a great dataset selection, we are looking forward for the final outcome.

**Comment by Jothish21** [comment]
--> Added project title to Nav bar
--> Added author details(group member detail) in the about page 
--> Added include=FALSE as parameter in code chunk
--> Removed (') colons when describing the variable in data
--> Added a small explanation about the scales which are representing the magnitude of the tornadoes
--> Removed the labels in the code chunks present in proposal page.
--> The team has agreed to move forward with the current approach of displaying alley maps for the first question and utilizing heat-maps or barplots for the second question, a suggestion previously discussed and proposed by Greg.
