### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/project-01-Aes-thetics-Squad#3]
Dear Aes-thetics-Squad: Below is the score breakdown for your proposal. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |      3  |
| Proposal | 5         |       5 |
| Workflow | 1         |       1 |
| Teamwork | 1         |        1|
| Total    | 10        |       10 |

Good work, just some minor issues to fix: 
1. "yr: Year." Always give the range in years. 
2. use `` around column names to denote variables to help break them from the text. 
3. State the data type of each column.

**Comment by Priyarsha31** [comment]
Made the changes, issue resolved.

**Comment by Gchism94** [comment]
Looks great, your final proposal score is 9.5/10.
