### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by KashyapNadendla** [INFO526-DataViz/project-01-Aes-thetics-Squad#4]
The following is the peer review of the Presentation proposal by R-tisans of Visual. The team members that participated in this review are 

- Kashyap Sai Prasad Nadendla- @KashyapNadendla 
- Visalakshi Prakash Iyer - @visalakshi2001
- Rahul Bangad - @rahulbangad98 
- Athira Thekkemadathil Anilkumar - @AthiraThekkemadathilAnilkumar

- Content: Is the research question well designed and is the data being used relevant to the research question?

  Yes, there is no apparent change required in the content analysis. The team has researched about their topic and data thoroughly. They have also analyzed the plot interpretation with respect to occurrences in the real time.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

   Yes, the visualizations used were suitable for the analysis. For the first question, there are two line plots that compare the changing magnitude of tornadoes and a bar plot as well. However, it would have been better if there was an annotation in the first line plot on the year where the measuring scale for the tornado changes. It is only a small detail for a more precise interpretation. The contour plot animation was excellent, showing trends across location.
The colors look good in the normal display, however it looks a little too vivid on the projector.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

  Yes, the project seems to be pretty well thought out. The team has done thorough research on their topic, along with coming up with suitable aspects to analyze. 

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

  The team had done an excellent job with the plots and slide content. The flow of the slides could have been tweaked to match the flow of presentation (highlighted in the next point). They can also reduce the size of text on the dataset characteristics slide. As well as change the font-size a bit to match the presentation aspect ratio. This doesn't take away the fact that their plots were amazingly done. Such small details will just enhance their hard work further.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

  The team presented their slides really well. The opening was great. There were a few moments were the flow was mixed because the questions slide was kept before the dataset description and characteristics slide. Yet everyone did an excellent job in putting forth their insights.

**Comment by Gchism94** [comment]
I'm awarding 4.5/5 points based on the peer-review
